version: '3'
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      PUBLIC_CAPTCHA_SITE_KEY: "10000000-ffff-ffff-ffff-000000000001"
      CAPTCHA_SECRET_KEY: "0x0000000000000000000000000000000000000000"
      MAIL_USER: ""
      MAIL_PASSWORD: ""
      BLOG_URL: "https://blog.mpesteban.dev"

